library(pafr)
library(ggplot2)
getwd()

ucr_atcc <- read_paf('ucr_atcc_asm5.paf')
ucr_cbs6939 <- read_paf('ucr_cbs6936_asm5.paf')
ucr_fda <-  read_paf('ucr_fda_asm5.paf')
ucr_mj12 <- read_paf('ucr_mj12_asm5.paf')
ucr_sanglaard <-  read_paf('ucr_sanglaard_asm5.paf')
dotplot(ucr_atcc, label_seqs = T, order_by = "qstart") + theme_bw()
dotplot(ucr_cbs6939, label_seqs = T, order_by = "qstart") + theme_bw()
dotplot(ucr_fda, label_seqs = T, order_by = "qstart") + theme_bw()
dotplot(ucr_mj12, label_seqs = T, order_by = "qstart") + theme_bw()
dotplot(ucr_sanglaard, label_seqs = T, order_by = "qstart") + theme_bw()
plot_coverage(ucr_atcc, fill='qname') + scale_fill_brewer(palette = "Set1")
plot_coverage(ucr_cbs6939, fill='qname') + scale_fill_brewer(palette = "Set1")
plot_coverage(ucr_fda, fill='qname') + scale_fill_brewer(palette = "Set1")
plot_coverage(ucr_mj12, fill='qname') + scale_fill_brewer(palette = "Set1")
plot_coverage(ucr_sanglard, fill='qname') + scale_fill_brewer(palette = "Set1")
